<table>
<tr>                                                                                   
     <th>
         <div style='padding:15px;color:#030aa7;font-size:240%;text-align: center;font-style: italic;font-weight: bold;font-family: Georgia, serif'><a href="https://www.kaggle.com/datasets/pitt/contagious-diseases">Project Tycho-Contagious Diseases</a></div>
     </th>
     <th><img src=https://raw.githubusercontent.com/rbizoi/IntelligenceEnDonneesDeSante/refs/heads/main/images/tycho_cd.jpg width="96"></th>
 </tr>
</table>

# <b><div style='padding:15px;background-color:#d8dcd6;color:#030aa7;font-size:120%;text-align: left'>Introduction</div></b>
## <b><div style='padding:15px;background-color:#d8dcd6;color:#030aa7;font-size:120%;text-align: left'>Import libriries </div></b>

In [1]:
import pandas as pd, numpy as np, seaborn as sns, warnings, os
from datetime import datetime as dt
from matplotlib import pyplot as plt
import matplotlib.font_manager as fm
import matplotlib.patheffects as path_effects

import plotly.express as px
import plotly.graph_objs as go

font1 = fm.FontProperties(size=20)
font2 = fm.FontProperties(size=24)

warnings.filterwarnings(action="ignore")

if int(str(sns.__version__).split('.')[1]) > 8 : 
    plt.style.use('seaborn-v0_8-darkgrid')
else:
    plt.style.use('seaborn-darkgrid')
sns.set(font_scale=3)

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)  
pd.set_option('display.max_rows', None)

# <b><div style='padding:15px;background-color:#d8dcd6;color:#030aa7;font-size:120%;text-align: left'>Lecture des données</div></b>

In [2]:
!ls -al "../donnees/Project Tycho-Contagious Diseases"

total 22976
drwxrwxrwx  3 razvan razvan    4096 nov.  24 18:52  .
drwxrwxrwx 35 razvan razvan    4096 nov.  18 12:04  ..
-rwxrwxrwx  1 razvan razvan 2771718 oct.   7  2021 'archive(23).zip'
-rwxrwxrwx  1 razvan razvan 3463284 sept. 20  2019  hepatitis.csv
drwxrwxr-x  2 razvan razvan    4096 nov.  24 18:52  .ipynb_checkpoints
-rwxrwxrwx  1 razvan razvan 5053296 sept. 20  2019  measles.csv
-rwxrwxrwx  1 razvan razvan 2184265 sept. 20  2019  mumps.csv
-rwxrwxrwx  1 razvan razvan 3928121 sept. 20  2019  pertussis.csv
-rwxrwxrwx  1 razvan razvan 2570114 sept. 20  2019  polio.csv
-rwxrwxrwx  1 razvan razvan     345 oct.   7  2021 'Project Tycho Contagious Diseases Kaggle.URL'
-rwxrwxrwx  1 razvan razvan 1758930 sept. 20  2019  rubella.csv
-rwxrwxrwx  1 razvan razvan 1730116 sept. 20  2019  smallpox.csv

In [3]:
repertoire="../donnees/Project Tycho-Contagious Diseases"
fichiers = {}
maladies = {'hepatitis':'hépatite','measles':'rougeole','mumps':'oreillons','pertussis':'coqueluche','polio':'poliomyélite','rubella':'rubéole','smallpox':'variole'}
for fichier in os.listdir(repertoire): 
    if fichier[-4:] == '.csv' :
        fichiers[maladies[fichier[:-4]]] = pd.read_csv(os.path.join(repertoire, fichier)).set_index(['week', 'state', 'state_name'])

for maladie in fichiers:
    fichiers[maladie].rename(columns={'disease':maladie, 'cases':f'{maladie}_c', 'incidence_per_capita':f'{maladie}_ic'},inplace=True)
    print(f'{maladie} ',end='\t')
    print(f'{fichiers[maladie].shape[0]}    ',end='\t')
    print(f'{fichiers[maladie].reset_index()[['week', 'state', 'state_name']].drop_duplicates().shape[0]}     ',end='\t')
    print(f'{fichiers[maladie].shape[0] - fichiers[maladie].reset_index()[['week', 'state', 'state_name']].drop_duplicates().shape[0]}')

oreillons 	69754    	69754     	0
hépatite 	90839    	90839     	0
variole 	50916    	50916     	0
rubéole 	53205    	53205     	0
poliomyélite 	81531    	81518     	13
coqueluche 	109072    	109072     	0
rougeole 	145167    	145165     	2

## <b><div style='padding:15px;background-color:#d8dcd6;color:#030aa7;font-size:120%;text-align: left'>Poliomyélite</div></b>

In [4]:
fichiers['poliomyélite'].reset_index(inplace=True)
fichiers['poliomyélite']['n'] = fichiers['poliomyélite'].groupby(['week','state','state_name']).week.transform('count') 
fichiers['poliomyélite'] = fichiers['poliomyélite'][(fichiers['poliomyélite'].n != 2)|(fichiers['poliomyélite'].poliomyélite_c != r'\N')]  
fichiers['poliomyélite'].drop(columns='n',inplace=True)
fichiers['poliomyélite'].set_index(['week', 'state', 'state_name'], inplace=True)
fichiers['poliomyélite'].shape[0]

81518

In [5]:
fichiers['poliomyélite'].poliomyélite_c[fichiers['poliomyélite'].poliomyélite_c == r'\N'] = 0
fichiers['poliomyélite'].poliomyélite_c = fichiers['poliomyélite'].poliomyélite_c.astype('int32')

## <b><div style='padding:15px;background-color:#d8dcd6;color:#030aa7;font-size:120%;text-align: left'>Rougeole</div></b>

In [6]:
fichiers['rougeole'].reset_index(inplace=True)
fichiers['rougeole']['n'] = fichiers['rougeole'].groupby(['week','state','state_name']).week.transform('count') 
fichiers['rougeole'][fichiers['rougeole'].n > 1]

          week state     state_name rougeole  rougeole_c  rougeole_ic  n
140443  199551    MA  MASSACHUSETTS  MEASLES           1         0.02  2
140444  199551    MA  MASSACHUSETTS  MEASLES           1         0.02  2
140456  199551    WA     WASHINGTON  MEASLES           1         0.02  2
140457  199551    WA     WASHINGTON  MEASLES           1         0.02  2

In [7]:
fichiers['rougeole'] = fichiers['rougeole'].drop_duplicates()
fichiers['rougeole'].drop(columns='n',inplace=True)
fichiers['rougeole'].set_index(['week', 'state', 'state_name'], inplace=True)

In [8]:
fichiers['rougeole'].shape[0]

145165

## <b><div style='padding:15px;background-color:#d8dcd6;color:#030aa7;font-size:120%;text-align: left'>Jointure</div></b>

In [9]:
cles = list(fichiers.keys())
nom = cles[0]
donnees = fichiers[nom] 

cle_avant = cles[0]
for cle in cles[1:]:
    donnees = donnees.join(fichiers[cle], how='outer') # ,lsuffix = f'_{cle_avant}', rsuffix = f'_{cle}'
    cle_avant = cle

In [10]:
for maladie in fichiers:
    print(f'{maladie} \t fichier {fichiers[maladie].shape[0]}   \t donnees {sum(~donnees[maladie].isna())}')

oreillons 	 fichier 69754   	 donnees 69754
hépatite 	 fichier 90839   	 donnees 90839
variole 	 fichier 50916   	 donnees 50916
rubéole 	 fichier 53205   	 donnees 53205
poliomyélite 	 fichier 81518   	 donnees 81518
coqueluche 	 fichier 109072   	 donnees 109072
rougeole 	 fichier 145165   	 donnees 145165

In [11]:
donnees.shape

(209823, 21)

In [12]:
donnees.reset_index(inplace=True)

In [13]:
donnees['année'] = donnees.week.apply(lambda x : str(x)[:4])

In [14]:
donnees.head()

,week,state,state_name,oreillons,oreillons_c,oreillons_ic,hépatite,hépatite_c,hépatite_ic,variole,variole_c,variole_ic,rubéole,rubéole_c,rubéole_ic,poliomyélite,poliomyélite_c,poliomyélite_ic,coqueluche,coqueluche_c,coqueluche_ic,rougeole,rougeole_c,rougeole_ic,année
0,192801,AL,ALABAMA,NaN,NaN,NaN,NaN,NaN,NaN,SMALLPOX,1.0,0.04,NaN,NaN,NaN,POLIO,0.0,0.00,NaN,NaN,NaN,MEASLES,97.0,3.67,1928
1,192801,AR,ARKANSAS,NaN,NaN,NaN,NaN,NaN,NaN,SMALLPOX,7.0,0.38,NaN,NaN,NaN,POLIO,0.0,0.00,NaN,NaN,NaN,MEASLES,76.0,4.11,1928
2,192801,AZ,ARIZONA,NaN,NaN,NaN,NaN,NaN,NaN,SMALLPOX,0.0,0.00,NaN,NaN,NaN,POLIO,0.0,0.00,NaN,NaN,NaN,MEASLES,8.0,1.90,1928
3,192801,CA,CALIFORNIA,NaN,NaN,NaN,NaN,NaN,NaN,SMALLPOX,18.0,0.34,NaN,NaN,NaN,POLIO,9.0,0.17,NaN,NaN,NaN,MEASLES,74.0,1.38,1928
4,192801,CO,COLORADO,NaN,NaN,NaN,NaN,NaN,NaN,SMALLPOX,31.0,3.06,NaN,NaN,NaN,POLIO,4.0,0.39,NaN,NaN,NaN,MEASLES,85.0,8.38,1928

In [15]:
donnees[['oreillons_c', 'hépatite_c', 'variole_c', 'rubéole_c', 'poliomyélite_c', 'coqueluche_c', 'rougeole_c', 'année']].groupby('année').sum()

,oreillons_c,hépatite_c,variole_c,rubéole_c,poliomyélite_c,coqueluche_c,rougeole_c
année,,,,,,,
1928,0.0,0.0,36470.0,0.0,4756.0,0.0,483337.0
1929,0.0,0.0,38389.0,0.0,2746.0,0.0,339061.0
1930,0.0,0.0,45728.0,0.0,8964.0,0.0,384597.0
1931,0.0,0.0,28708.0,0.0,15743.0,0.0,438435.0
1932,0.0,0.0,10740.0,0.0,3829.0,0.0,390114.0
1933,0.0,0.0,6164.0,0.0,4927.0,0.0,380394.0
1934,0.0,0.0,5139.0,0.0,7274.0,0.0,727096.0
1935,0.0,0.0,7489.0,0.0,10733.0,0.0,721002.0
1936,0.0,0.0,7262.0,0.0,4326.0,0.0,280942.0
1937,0.0,0.0,11090.0,0.0,9480.0,0.0,293855.0
1938,0.0,0.0,14727.0,0.0,4027.0,209076.0,820087.0
1939,0.0,0.0,11112.0,0.0,7325.0,185646.0,427103.0
1940,0.0,0.0,4539.0,0.0,8220.0,172550.0,288894.0
1941,0.0,0.0,1401.0,0.0,8636.0,202413.0,755498.0
1942,0.0,0.0,957.0,0.0,4108.0,177707.0,486852.0
1943,0.0,0.0,884.0,0.0,10059.0,178483.0,552889.0
1944,0.0,0.0,531.0,0.0,17802.0,105550.0,533679.0
1945,0.0,0.0,387.0,0.0,13042.0,119698.0,146822.0
1946,0.0,0.0,353.0,0.0,20944.0,100515.0,615723.0
1947,0.0,0.0,168.0,0.0,12136.0,148127.0,211679.0
1948,0.0,0.0,446.0,0.0,26797.0,75625.0,508435.0
1949,0.0,0.0,67.0,0.0,42349.0,68098.0,606202.0
1950,0.0,0.0,42.0,0.0,33204.0,115525.0,301379.0
1951,0.0,0.0,19.0,0.0,27920.0,64277.0,502859.0
1952,0.0,0.0,16.0,0.0,49862.0,53962.0,588052.0
1953,0.0,0.0,0.0,0.0,35281.0,34871.0,433993.0
1954,0.0,0.0,0.0,0.0,39392.0,61019.0,686492.0
1955,0.0,0.0,0.0,0.0,27103.0,61770.0,529705.0
1956,0.0,0.0,0.0,0.0,15747.0,0.0,616050.0
1957,0.0,0.0,0.0,0.0,6197.0,0.0,460821.0
1958,0.0,0.0,0.0,0.0,6074.0,0.0,707368.0
1959,0.0,0.0,0.0,0.0,5475.0,0.0,374503.0
1960,0.0,0.0,0.0,0.0,3303.0,0.0,432221.0
1961,0.0,0.0,0.0,0.0,1332.0,0.0,402551.0
1962,0.0,0.0,0.0,0.0,908.0,0.0,476141.0
1963,0.0,0.0,0.0,0.0,427.0,0.0,332057.0
1964,0.0,0.0,0.0,0.0,112.0,0.0,431259.0
1965,0.0,0.0,0.0,0.0,55.0,0.0,264303.0
1966,0.0,32416.0,0.0,44929.0,95.0,0.0,201064.0
1967,0.0,38280.0,0.0,42154.0,43.0,0.0,59258.0
1968,142744.0,45204.0,0.0,47909.0,56.0,0.0,22879.0
1969,81373.0,46012.0,0.0,52746.0,0.0,0.0,24190.0
1970,96916.0,55188.0,0.0,53906.0,0.0,0.0,45697.0
1971,114180.0,58959.0,0.0,42612.0,0.0,0.0,71878.0
1972,65594.0,48618.0,0.0,23158.0,0.0,0.0,30121.0
1973,62736.0,48552.0,0.0,27332.0,0.0,0.0,25657.0
1974,54987.0,38051.0,0.0,11045.0,0.0,1627.0,21072.0
1975,57749.0,33634.0,0.0,15584.0,0.0,1389.0,23845.0
1976,37625.0,32296.0,0.0,11960.0,0.0,863.0,39001.0
1977,19355.0,28832.0,0.0,19744.0,0.0,1697.0,49654.0
1978,15720.0,26847.0,0.0,16054.0,0.0,1687.0,26884.0
1979,13780.0,26575.0,0.0,11016.0,0.0,1276.0,12781.0
1980,8248.0,18754.0,0.0,3692.0,0.0,1377.0,13047.0
1981,4394.0,21688.0,0.0,2051.0,0.0,1002.0,2947.0
1982,5120.0,20362.0,0.0,2136.0,0.0,1356.0,1709.0
1983,3171.0,19744.0,0.0,941.0,0.0,2152.0,1182.0
1984,2771.0,19423.0,0.0,733.0,0.0,1995.0,2200.0
1985,2766.0,17179.0,0.0,599.0,0.0,2973.0,2415.0
1986,5371.0,16084.0,0.0,470.0,0.0,3927.0,5725.0
1987,10852.0,21882.0,0.0,308.0,0.0,2342.0,3192.0
1988,4659.0,12327.0,0.0,198.0,0.0,2943.0,2851.0
1989,5341.0,23514.0,0.0,372.0,0.0,3293.0,15227.0
1990,4582.0,23487.0,0.0,968.0,0.0,3552.0,21734.0
1991,3713.0,17239.0,0.0,802.0,0.0,2330.0,8122.0
1992,2143.0,14546.0,0.0,143.0,0.0,2712.0,1840.0
1993,1372.0,10865.0,0.0,156.0,0.0,5582.0,213.0
1994,1450.0,13927.0,0.0,182.0,0.0,3164.0,689.0
1995,778.0,22317.0,0.0,174.0,0.0,3973.0,212.0
1996,549.0,24496.0,0.0,193.0,0.0,5937.0,465.0
1997,545.0,15221.0,0.0,163.0,0.0,4790.0,533.0
1998,530.0,15493.0,0.0,209.0,0.0,4443.0,58.0
1999,294.0,11848.0,0.0,167.0,0.0,4292.0,61.0
2000,272.0,9429.0,0.0,138.0,0.0,4965.0,56.0
2001,215.0,8859.0,0.0,18.0,0.0,4329.0,73.0
2002,215.0,7779.0,0.0,4.0,0.0,7801.0,14.0
2003,0.0,6796.0,0.0,0.0,0.0,6922.0,0.0
2004,0.0,5449.0,0.0,0.0,0.0,17834.0,0.0
2005,0.0,4519.0,0.0,0.0,0.0,21146.0,0.0
2006,0.0,2656.0,0.0,0.0,0.0,10532.0,0.0
2007,0.0,2243.0,0.0,0.0,0.0,6999.0,0.0
2008,0.0,2030.0,0.0,0.0,0.0,6754.0,0.0
2009,0.0,1580.0,0.0,0.0,0.0,8940.0,0.0
2010,0.0,4060.0,0.0,0.0,0.0,14112.0,0.0
2011,0.0,1102.0,0.0,0.0,0.0,11100.0,0.0